UserManagementMvc 8-12-2023/UserMvc/Models/ViewModels/CreateUserVM.cs
using System.ComponentModel.DataAnnotations;

namespace UserMvc.Models.ViewModels
{
    public class CreateUserVM
    {
        [Required]
        public string name { get; set; }

        public string email { get; set; }

        [Required]
        public string password { get; set; }

        public int Roleid { get; set; }

        public IFormFile Photo { get; set; }
    }
}

UserManagementMvc 8-12-2023/UserMvc/Models/ViewModels/UserLogs.cs
namespace UserMvc.Models.ViewModels
{
    public class UserLogs
    {
        public string Username { get; set; }

        public string Email { get; set; }

        public DateTime? LoginInfo { get; set; }
    }
}

UserManagementMvc 8-12-2023/UserMvc/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace UserMvc.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Authentication()
        {
            return View();
        }

    }
}

UserManagementMvc 8-12-2023/UserMvc/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace UserMvc.Controllers
{
    public class UserController : Controller
    {
        // GET: UserController
        public ActionResult Index()
        {
            return View();
        }


        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Logs()
        {
            return View();
        }

        // POST: UserController/Create
        

        // GET: UserController/Edit/5
        public ActionResult Edit(string Email)
        {
            ViewData["editgemail"] = Email;
            return View();
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        [HttpDelete]
        public ActionResult Delete(string Email)
        {

            return View();
        }

        
    }
}

UserManagementMvc 8-12-2023/UserMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UserManagementMvc 8-12-2023/UserMvc/Views/Login/Authentication.cshtml
[5:05 PM] G, Nithish
<link rel="stylesheet" href="~/css/AuthenticationStyleSheet.css" />

<div class="superimg">
</div>

<div class="auth"><h1>AUTHENTICATION</h1></div>

<h5>Verification code has been sent to the registered Email</h5>

<div class="card">

    <div class="card-body">

        <div class="row">

            <div class="captcha-container">

                <form action="#" method="post" id="captcha-form" onsubmit="return validateCaptcha()">

                    <div class="captcha">

                        <span class="captcha-text" id="captcha-text">AKASH</span>

                    </div>

                    <label for="user-input">Enter the above CAPTCHA Code:</label>

                    <input type="text" id="user-input" name="user-input" required>

                    <center>

                        <button type="submit" id="subbtn">Submit</button>

                        <button type="button" id="refresh-btn" onclick="refreshCaptcha()">Refresh</button>

                    </center>

                </form>


            </div>

            <div class="col-lg-12">

                <div class="form-group">

                    <label>OTP</label>

                    <input type="text" class="form-control" id="txtotp" style="border:1px solid black" />

                </div>

            </div>

        </div>

    </div>

</div>

<br />

<div class="card-footer">

    <a onclick="ProceedVerify()" class="btn btn-primary">Verify</a>

</div>

<p class="succ-msg" id="succmsg" style="color:red"></p>

<!-- Add this div for displaying the warning message -->

<div class="warning-msg" id="warning-msg"></div>

<script src="/js/CaptchaJavaScript.js"></script>

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<script type="text/javascript">

    var js = jQuery.noConflict(true);

    function validateCaptcha() {

        var userInput = document.getElementById('user-input').value;

        var captchaText = document.getElementById('captcha-text').innerText;

        if (userInput.toUpperCase() === captchaText.toUpperCase()) {

            return true; // CAPTCHA is verified

        } else {

            var warningMsg = document.getElementById('warning-msg');

            warningMsg.textContent = 'Invalid CAPTCHA code. Please try again.';

            refreshCaptcha(); // Refresh CAPTCHA on failure

            return false;

        }

    }

    // Revised ProceedVerify function

    function ProceedVerify() {

        var isproceed = true;

        var urlParams = new URLSearchParams(window.location.search);

        var user = urlParams.get('username');

        var _otp = $('#txtotp');

        var otp = _otp.val();

        if (otp == null || otp.trim() == '') {

            _otp.css('border-color', 'red');

            isproceed = false;

        } else {

            _otp.css('border-color', '#ccc');

        }

        if (isproceed) {

            var succmsg = document.getElementById('succmsg');

            var _obj = {

                username: user,

                code: otp

            };

            $.ajax({

                type: 'POST',

                url: 'https://localhost:7010/api/Authentication/login-2FA',

                data: JSON.stringify(_obj),

                contentType: 'application/json; charset=utf-8',

                dataType: 'json',

                success: function (data) {

                    if (data && data.token) {

                        localStorage.setItem('token', data.token);

                        if (data.role === 'SuperAdmin') {

                            // Redirect to the next page for SuperAdmin

                            window.location.href = '/User/Index';

                        } else {

                            window.location.href = '/Login/Index';

                            succmsg.textContent = 'Access denied. User is not a Super Admin';

                            return false;

                        }

                    } else {

                        // Handle other scenarios or errors

                    }

                },

                error: function (xhr, textStatus, errorThrown) {
                    // Display error message on the page
                    //alert('Invalid verification Code.');
                    window.location.href = '/Login/Index';
                    succmsg.textContent = 'Invalid Verification Code.';
                    return false;

                }

            });

        }

    }

</script>

UserManagementMvc 8-12-2023/UserMvc/Views/Login/Index.cshtml
<style type="text/css">
     .card {
         width: 50%;
         height:70%;
         margin-left: 0%;
         margin-top: 5%
     }
</style>
<link rel="stylesheet" href="~/css/loginIndexStyleSheet.css" />
<center><h1>FEATURE MESH</h1></center>
<div class="superimg">
</div>
<div class="para">
    <h3>Welcome, Super Admin</h3>

</div>
<form onclick="return validate()">
<div class="card">
    <div class="card-header">
        <center><h2>Super Admin</h2></center>
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label>Username</label>
                    <input class="form-control" id="txtusername" required/>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" class="form-control" id="txtpwd" required/>
                </div>
            </div>

        </div>
    </div>
    <div class="card-footer">
        <center><a onclick="ProceedLogin()" class="btn btn-primary">Login</a></center>
    </div>
    
</div>
<br />
    <p id="warningMessage" class="warning-message"></p>
    <p id="invalidMessage" class="invalid-message"></p>
</form>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">

    var js = jQuery.noConflict(true);


    function ProceedLogin() {

        var isproceed = true;

        var _user = $('#txtusername');
        var _pwd = $('#txtpwd');
        

        var user = _user.val();
        var pwd = _pwd.val();

        if (user == null || user == '') {
            _user.css('border-color', 'red');
            isproceed = false;

         
        } else {
            _user.css('border-color', '#ccc');
           
        }
        if (pwd == null || pwd == '') {
            _pwd.css('border-color', 'red');
            isproceed = false;
           
        } else {
            _pwd.css('border-color', '#ccc');
            
        }
        if (isproceed) {

            var _obj = new Object();
            var invalidMessage = document.getElementById('invalidMessage');
            _obj.Username = user;
            _obj.Password = pwd;
            

            $.ajax({
                type: 'POST',
                url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/login',
                data: JSON.stringify(_obj),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                async: false,
                success: function (data) {
                    if (data && data.status === "Success") {
                        localStorage.setItem('token', data.token);
                        
                        window.location.href = '/Login/Authentication?username=' + encodeURIComponent(user);
                    }
                    else{

                    }
                },
                error: function (xhr, textStatus, errorThrown) {
                    
                    invalidMessage.textContent = 'Invaild User-name or Password';
                    return false;
                    
                }
            })

        }


    }
    function validate() { 
        var username = document.getElementById('txtusername').value;
        var password = document.getElementById('txtpwd').value;
        var warningMessage = document.getElementById('warningMessage');

        if (username.trim() === '' || password.trim() === '') {
            warningMessage.textContent = 'Please enter both user-name and password';
            return false;
        }
    }
</script>           

UserManagementMvc 8-12-2023/UserMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UserMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserMvc.styles.css" asp-append-version="true" />
</head>
<body>
   @*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UserMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UserManagementMvc 8-12-2023/UserMvc/Views/User/Create.cshtml
<style type="text/css">
     .card {
         width: 38%;
         margin: 60px 0px 0px 600px;
         /* width: 60%;
              margin-left: 20%;
              margin-top: 5% */
     }
</style>
<link rel="stylesheet" href="~/css/UserCraeteStyleSheet.css" />
<h1>ADD USER</h1>
<div class="imagi">
</div>
<div class="boxi">
</div>
<form onclick="return create()">
    <div class="card">
        <div class="card-header">
            @* <center><h2>User Login</h2></center> *@
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Username</label>
                        <input class="form-control" id="txtusername" />
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" id="txtemail" />
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Password</label>
                        <input class="form-control" id="txtpass" />
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" id="txtrole">
                            <option value="Select-Role">Select Role</option>
                            <option value="Admin">Admin</option>
                            <option value="Users">User</option>
                        </select>
                    </div>
                </div>

            </div>
        </div>
        <div class="card-footer">
            <center>
                <a onclick="create()" class="btn btn-primary">Add</a>
                <a asp-controller="User" asp-action="Index" class="btn btn-danger">Back</a>
            </center>
        </div>
        <p id="successdmsg" class="successd-msg"></p>

    </div>
    <p id="successdmsg" class="successd-msg"></p>
</form>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">

    var js = jQuery.noConflict(true);
    function create() {
        var isproceed = true;

        var _user = $('#txtusername');
        var _email = $('#txtemail');
        var _pwd = $('#txtpass');
        var _role = $('#txtrole');


        var user = _user.val();
        var email = _email.val();
        var pwd = _pwd.val();
        var role = _role.val();

        if (user == null || user == '') {
            _user.css('border-color', 'red');
            isproceed = false;
        } else {
            _user.css('border-color', '#ccc');
        }
        if (email == null || email == '') {
            _email.css('border-color', 'red');
            isproceed = false;
        } else {
            _email.css('border-color', '#ccc');
        }
        if (pwd == null || pwd == '') {
            _pwd.css('border-color', 'red');
            isproceed = false;
        } else {
            _pwd.css('border-color', '#ccc');
        }
        if (role == null || role == '') {
            _role.css('border-color', 'red');
            isproceed = false;
        } else {
            _role.css('border-color', '#ccc');
        }
        if (isproceed) {

            var _obj = new Object();
            var successdmsg = document.getElementById('successdmsg');
            _obj.Username = user;
            _obj.Email = email;
            _obj.Password = pwd;
            _obj.Role = role;

            $.ajax({
                type: 'POST',
                url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication',
                data: JSON.stringify(_obj),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                async: false,
                success: function (data) {
                    if (data != null) {
                        localStorage.setItem('token', data.token);
                        window.location.href = '/User/Index'
                        // alert('User Added Successfully.')
                        successdmsg.textContent = 'User Added Successfully';
                        return false;
                    }
                },
                failure: function (error) {
                    // alert('Failed to create User')
                    successdmsg.textContent = 'Failed to add user';
                    return false;
                }
            })

        }


    }
</script>

UserManagementMvc 8-12-2023/UserMvc/Views/User/Edit.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Customer</title>

    <style type="text/css">
        .card {
            width: 40%;
            margin-top: 100px;
            /* width: 60%;
            margin-left: 20%;
            margin-top: 5% */
        }
    </style>
    <link rel="stylesheet" href="~/css/EditStyleSheet.css" />
</head>
<body>
    <h1>EDIT USER</h1>

    <div class="yel">
    </div>
    <div class="pic">
    </div>
    <div class="card">
        <div class="card-header">
            <center><h2>Edit User</h2></center>
        </div>
        <div class="card-body">

            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Existing Email</label>
                        <input disabled="disabled" value="@ViewData["editgemail"]" class="form-control" id="txtgemail" />
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Name</label>
                        <input class="form-control" id="txtname" />
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" id="txtemail" />
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" id="txtrole">
                            <option value="Select-Role">Select Role</option>
                            <option value="Admin">Admin</option>
                            <option value="Users">User</option>
                        </select>
                    </div>
                </div>

             

            </div>
        </div>
        <div class="card-footer">
            <center>
            <a onclick="SaveUser()" class="btn ">Save</a>
            <a asp-controller="User" asp-action="Index" class="btn ">Back</a>
            </center>
        </div>
    </div>
    <p id="dispmsg" class="disp-msg"></p>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var codes = $('#txtgemail').val();

            if (codes != '' && codes != null) {
                $.ajax({
                    type: 'GET',
                    url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/GetUserByEmail?email=' + codes,
                    // contentType: "application/json; charset=utf-8",
                    // dataType: "json",
                    async: false,
                    success: function (data) {
                        if (data != null) {
                            $('#txtname').val(data.name);
                            $('#txtemail').val(data.email);
                            $('#txtrole').val(data.role);
                        }
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            }
        });

        function SaveUser() {
            var isproceed = true;

            var _user = $('#txtname');
            var _email = $('#txtemail');
            var _role = $('#txtrole');



                var user = _user.val();
                var email = _email.val();
                
                var role = _role.val();

                if (user == null || user == '') {
                    _user.css('border-color', 'red');
                    isproceed = false;
                } else {
                    _user.css('border-color', '#ccc');
                }
                if (email == null || email == '') {
                    _email.css('border-color', 'red');
                    isproceed = false;
                } else {
                    _email.css('border-color', '#ccc');
                }
                
                if (role == null || role == '') {
                    _role.css('border-color', 'red');
                    isproceed = false;
                } else {
                    _role.css('border-color', '#ccc');
                }
                if (isproceed) {

                    var _obj = new Object();
                    var dispmsg = document.getElementById('dispmsg');
                    _obj.Username = user;
                    _obj.Email = email;
                    _obj.Role = role;


                    $.ajax({
                        type: 'PUT',
                    url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/EditUser',
                        data: JSON.stringify(_obj),
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        async: false,
                        success: function (data) {
                            if (data != null) {
                                localStorage.setItem('token', data.token);
                                window.location.href = '/User/Index'
                                // alert('User Edited Successfully.')
                                dispmsg.textContent = 'User Edited Successfully';
                                return false;
                            }
                        },
                        failure: function (error) {
                            // alert('Failed to edit User')
                            dispmsg.textContent = 'Failed to edit User';
                            return false;
                        }
                    })

                }

            
        }
    </script>

</body>
</html>

UserManagementMvc 8-12-2023/UserMvc/Views/User/Index.cshtml
<style>
    .card {
        /*position: fixed;*/
        margin: 10px 0px 0px 70px;
        width: 90%;
    }

    #logout
    {
        margin:0px 0px 0px 600px;
    }
</style>
<link rel="stylesheet" href="~/css/UserIndexStyleSheet.css" />
<center><p id="delmsg" class="del-msg"></p></center>
<div class="card">
    <div class="card-header">
        <center><h2>User</h2></center>
    </div>
    <div class="card-body">
        <div class="card-title">
            <a asp-controller="User" asp-action="Create" class="btn btn-success" style="background-color:white;color:black;border:2px solid black">Add New</a>         
            <a asp-controller="User" asp-action="Logs" class="btn btn-primary" id="logs" >User Logs</a>
            <a asp-controller="Login" asp-action="Index" class="btn btn-danger" id="logout">Logout</a>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table table-bordered" id="tblUser">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/UserIndexJavaScript.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">

    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        LoadUser()
    });

    function LoadUser() {
        tabledata = [];
        // var _token = localStorage.getItem('token');
        $.ajax({
            type: 'GET',
            url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/AllUsers',
            // headers: {
            //     'Authorization': 'bearer ' + _token
            // },
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (data) {

                $.each(data, function (key, value) {
                    var _edit = "<a class='btn' onclick='FunEdit(this)' style='background-color:white;color:black;border:2px solid black'>Edit</a>";
                    var _remove = "<a class='btn btn-danger' onclick='FunRemove(this)'>Delete</a>";
                    var _hdn = "<input id='hdncode' type='hidden' value=" + value.email + " />"
                    var _action = _hdn + _edit + " | " + _remove 
                    tabledata.push([value.id, value.name, value.email, value.role, _action])
                })
            },
            failure: function (error) {

            }
        })
        js('#tblUser').DataTable({
            data: tabledata
        })
    }
    function FunEdit(element) {
        var code = $(element).closest('tr').find('#hdncode').val();
        window.location.href = '/User/Edit?Email=' + code
    }

    function FunRemove(element) {
        var delmsg = document.getElementById('delmsg');
        var code = $(element).closest('tr').find('#hdncode').val();
        if (/* confirm('Do you want to remove?') */delmsg.textContent='User removed successful') {
            proceedremove(code)
        }
    }

    function proceedremove(code) {
        // var _token = localStorage.getItem('token');
        var delmsg = document.getElementById('delmsg');
        $.ajax({
            type: 'DELETE',
            url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/Delete?Email=' + code,
 
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (data) {
                debugger;
                
                    window.location.href = '/User';
                    // alert('Removed user Successfully.')
                delmsg.textContent = 'Removed user Successfully';
                return false;
                
            },
            failure: function (error) {

            }
        })
    }


</script>

UserManagementMvc 8-12-2023/UserMvc/Views/User/Logs.cshtml
<style>
    body{
        /* background-image: url('/grey background.jfif');
        background-repeat:no-repeat;
        background-size:cover; */
    }

    table{
        border:5px solid white;
    }

    .btn
    {
        color:black;
        background-color:white;
        border:2px solid black;
    }

    #tblUser tbody {
        background-color: white;
    }

        #tblUser tbody tr:nth-child(even) {
            background-color: lightgray;
        }

    #tblUser thead {
        background-color: lightblue;
    }
   /*  .row{
        border:2px solid black;
    } */

    .col-lg-12
    {
        margin:10px 0px 10px 0px;
    }
</style>
<center><h1>Logs</h1></center>

@* <p>
    <a asp-action="Index">Back</a>
</p> *@
<div class="row">
    <div class="col-lg-12">
        
        <table class="table table-bordered" id="tblUser">
            
            <thead>
                <tr>
                    
                    <th>Username</th>
                    <th>Email</th>
                    <th>User Logs</th>
                    
                </tr>
            </thead>
          
        </table>
    </div>

</div>
<br />
<center>
<p>
    <a asp-action="Index" class="btn">Back</a>
</p>
</center>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

<script type="text/javascript">

    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        LoadUser()
    });

    function LoadUser() {
        tabledata = [];
        // var _token = localStorage.getItem('token');
        $.ajax({
            type: 'GET',
            url: 'https://usermanagementapi-team4.azurewebsites.net/api/Authentication/LogDetails',
            
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            async: false,
            success: function (data) {

                $.each(data, function (key, value) {
                    
                    tabledata.push([value.name, value.email, value.dateTime])
                })
            },
            failure: function (error) {

            }
        })
        js('#tblUser').DataTable({
            data: tabledata
        })
    }

    </script>